version: '3.8'
services:
  postgres:
    container_name: postgres_prod
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: redis
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
  redis:
    image: redis:latest
    container_name: my-redis-r
    ports:
      - "6379:6379"
    restart: always