server:
  port: 8080
spring:
  application:
    name: university-enrolment-system-redis
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: redis
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    drop-first: false

redis:
  server:
    url: redis://localhost:6379
